apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureapp31-deployment-local
  labels:
    app: azureapp31-deployment-local
    component: netcore-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azureapp31
  template:
    metadata:
      labels:
        app: azureapp31
    spec:
      containers:
      - name: azureapp31
        image: vzavizion/azureapp31:1.0
        ports:
        - containerPort: 80