apiVersion: v1
kind: Service
metadata:
  name: azureapp31-deployment
  labels:
    app: azureapp31-deployment
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: azureapp31
    component: netcore-app      
  type: LoadBalancer        
